# The URL the site will be built for
base_url = "https://øsse.no"

title = "Øystein Walle"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default author for pages
author = "Øystein Walle"

theme = "hook"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

links = []
